import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "/src/components/header/NavBar";
import FooterContent from "/src/components/footer/FooterContent";
import LogoHeader from "/src/components/header/LogoHeader";
import UpdatedDatePanel from "@/components/header/UpdatedDatePanel";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO:Fix updatedDate component to responsive, problem with desktop vi as flex-column layout.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex flex-col sticky top-0 w-full bg-[#343434] md:h-16 md:flex-row md:justify-between">
          <LogoHeader />
          <UpdatedDatePanel />
          <NavBar />
        </header>
        {children}
        <footer>
          {/* TODO: Fix the height attribute to 76 px in desktop view. */}
          <FooterContent />
        </footer>
      </body>
    </html>
  );
}
