import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/header/NavBar";
import FooterContent from "./components/footer/FooterContent";
import LogoHeader from "./components/header/LogoHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex flex-col md:flex-row md:justify-between sticky top-0 w-full md:h-15 bg-[#343434]">
          <LogoHeader />
          <NavBar />
        </header>
        {children}
        <footer className="flex flex-col w-full py-4 gap-3">
          <FooterContent />
        </footer>
      </body>
    </html>
  );
}
