import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "/src/components/header/NavBar";
import FooterContent from "/src/components/footer/FooterContent";
import LogoHeader from "/src/components/header/LogoHeader";
import UpdatedDate from "@/components/header/UpdatedDate";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO:Fix updatedDate component to responsive, problem with desktop vi as flex-column layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex flex-col sticky top-0 w-full bg-[#343434] md:h-19 md:flex-row md:justify-between">
          <LogoHeader />
          <UpdatedDate />
          <NavBar />
        </header>
        {children}
        <footer className="flex flex-col w-full py-4 gap-3">
          <FooterContent />
        </footer>
      </body>
    </html>
  );
}
